### ISSUE TITLE
Unable to upload new events after the edit functionality was added

### ISSUE THREAD

**Issue by reidst** [DiscoTrayStudios/hendrix-today-uploader#15]
**Describe the bug**
Communications reported that the Excel uploader was not working after the database editing feature was added.

**To Reproduce**
I will look into this on my local machine and using the testing database to determine further details.

**Expected behavior**
The Excel upload page should not have been affected by the database editing feature.

**Comment by reidst** [comment]
I found the issue: the Excel-to-Firestore pipeline was calling a `DateTime` parsing function to try parsing an ISO 8601 `String`, but the function it was calling was one from the Firestore-to-Dart pipeline (on the other side of the app!) which only parsed `Timestamp`s. This was definitely my fault!

**Comment by mgoadric** [comment]
The date issue persists. Is there a way to add five hours to the dates that are processed? Or maybe 5 hours were subtracted accidentally? Or the Flutter update changed how the DateTime conversion functions work?

**Comment by reidst** [comment]
I think it's a time zone issue. The dates in the submission form have no time information, so when they are stored in Excel they are given `"00:00:00.000Z"`, midnight UTC, as their time component. This is preserved when reading into a Dart `DateTime` object, but when uploaded to Firestore this is translated to the equivalent time in CDT (our current time zone, or perhaps the time zone of nam5, our Firebase database location?)

I wonder if something changed in the app for these dates to not be read as UTC `DateTime`s before having the time information truncated and displayed. That would cause all the days to read as one day earlier.

**Comment by reidst** [comment]
I'm fairly certain I've figured it out now. The uploader just needs to truncate the time information from the dates and ensure the dates are in local time before uploading them.
